-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT *,
    RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) RNK
    FROM REST_INFO
) FOOD_RANK
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC