-- 코드를 입력하세요
SELECT INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(RV.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS INFO
JOIN REST_REVIEW AS RV
ON INFO.REST_ID = RV.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC