-- 코드를 작성해주세요
WITH RECURSIVE R AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT C.ID, C.PARENT_ID, P.GENERATION + 1 AS GENERATION
    FROM R P
    LEFT JOIN ECOLI_DATA C
    ON P.ID = C.PARENT_ID
    WHERE C.PARENT_ID IS NOT NULL
)

SELECT COUNT(*) COUNT, GENERATION
FROM R
LEFT JOIN ECOLI_DATA C
ON R.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION