-- 코드를 입력하세요
SELECT P.PRODUCT_ID, PRODUCT_NAME, (PRICE*SUM_AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
) AS O USING (PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID