-- 코드를 입력하세요
SELECT F.FLAVOR
FROM (
    SELECT TEMP.FLAVOR, SUM(TEMP.TOTAL_ORDER) AS TOTAL
    FROM (
        SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        UNION ALL
        SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
        FROM JULY
    ) AS TEMP
    GROUP BY TEMP.FLAVOR
    ORDER BY TOTAL DESC
    LIMIT 3
) AS F

