-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D
JOIN (
    SELECT *
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    ) AS S
ON D.SKILL_CODE & S.CODE > 0
ORDER BY ID