-- 코드를 입력하세요
SELECT MEMBER_NAME,	REVIEW_TEXT, REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN
(SELECT *
FROM REST_REVIEW
WHERE MEMBER_ID =
    (SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)
) AS R
ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT