-- 코드를 작성해주세요
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_TREE AS TREE
JOIN ITEM_INFO AS INFO
ON TREE.ITEM_ID = INFO.ITEM_ID
JOIN ITEM_INFO AS PARENT
ON TREE.PARENT_ITEM_ID = PARENT.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY TREE.ITEM_ID DESC
