-- 코드를 입력하세요
WITH COUNT_CAR AS (
    SELECT CAR_ID, COUNT(CAR_ID) AS TOTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
)
SELECT MONTH(START_DATE) MONTH, H.CAR_ID, COUNT(H.CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN COUNT_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE C.TOTAL_COUNT >= 5 AND START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY CAR_ID, MONTH
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC