-- 코드를 작성해주세요
WITH MAX_COLONY AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) YEAR_DEV
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(DIFFERENTIATION_DATE) YEAR, M.YEAR_DEV - E.SIZE_OF_COLONY YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN MAX_COLONY AS M
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV