-- 코드를 작성해주세요
SELECT INFO.ID, NAME.FISH_NAME, LENGTH
FROM FISH_INFO INFO
JOIN FISH_NAME_INFO NAME
ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO M WHERE INFO.FISH_TYPE = M.FISH_TYPE)
ORDER BY INFO.ID