-- 코드를 입력하세요
SELECT TITLE, A.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS,
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD as A
JOIN USED_GOODS_REPLY as B
ON A.BOARD_ID = B.BOARD_ID
WHERE YEAR(A.CREATED_DATE) = '2022' and MONTH(A.CREATED_DATE) = '10'
ORDER BY CREATED_DATE, TITLE;