-- 코드를 입력하세요
SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT *,
    RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')   
    ) AS R
WHERE RNK = 1
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC